// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientManagmentClient is the client API for ClientManagment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientManagmentClient interface {
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type clientManagmentClient struct {
	cc grpc.ClientConnInterface
}

func NewClientManagmentClient(cc grpc.ClientConnInterface) ClientManagmentClient {
	return &clientManagmentClient{cc}
}

func (c *clientManagmentClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Client.ClientManagment/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientManagmentServer is the server API for ClientManagment service.
// All implementations must embed UnimplementedClientManagmentServer
// for forward compatibility
type ClientManagmentServer interface {
	SayHello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedClientManagmentServer()
}

// UnimplementedClientManagmentServer must be embedded to have forward compatible implementations.
type UnimplementedClientManagmentServer struct {
}

func (UnimplementedClientManagmentServer) SayHello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedClientManagmentServer) mustEmbedUnimplementedClientManagmentServer() {}

// UnsafeClientManagmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientManagmentServer will
// result in compilation errors.
type UnsafeClientManagmentServer interface {
	mustEmbedUnimplementedClientManagmentServer()
}

func RegisterClientManagmentServer(s grpc.ServiceRegistrar, srv ClientManagmentServer) {
	s.RegisterService(&ClientManagment_ServiceDesc, srv)
}

func _ClientManagment_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagmentServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client.ClientManagment/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagmentServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientManagment_ServiceDesc is the grpc.ServiceDesc for ClientManagment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientManagment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Client.ClientManagment",
	HandlerType: (*ClientManagmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ClientManagment_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/clinet.proto",
}
